tk.Label(root, text="Name:").grid(row=0, column=0)
tk.Label(root, text="Email:").grid(row=1, column=0)
tk.Label(root, text="Date (YYYY-MM-DD):").grid(row=2, column=0)
tk.Label(root, text="Time (HH:MM):").grid(row=3, column=0)
tk.Label(root, text="Number of Guests:").grid(row=4, column=0)
